### ISSUE TITLE
multiple bots

### ISSUE THREAD

**Issue by testgitreps** [AquaPlaysYT/Fn_Bot_Commands#1]
how to run **multiple bots** on **same pc**?
hep me plz!!!!
can i do this by **duplicating folders** and starting bot?

**Comment by saeedalsnfawy** [comment]
I Think Yes

**Comment by testgitreps** [comment]
> 
> 
> I Think Yes

**Comment by ghost** [comment]
very bad way of doing that

**Comment by innowebka** [comment]
> 
> 
> very bad way of doing that

Why ?

**Comment by ghost** [comment]
> > very bad way of doing that
> 
> Why ?

it'll waste ur memory
