### ISSUE TITLE
Incompatible Build ID

### ISSUE THREAD

**Issue by ItzErrorYT** [AquaPlaysYT/Fn_Bot_Commands#2]
With the new update the build is incompatable and I can't invite or join the bots. PLEASE HELP!

**Comment by saeedalsnfawy** [comment]
Bot Works For Me Fine without any error 
on config edit netcl to this       "netcl" : "7786267",

**Comment by nooooo0** [comment]
> Bot Works For Me Fine without any error
> on config edit netcl to this "netcl" : "7786267",

no it dosent it keeps saying it

**Comment by saeedalsnfawy** [comment]
its working for me fine

**Comment by AquaPlaysYT** [comment]
posting a fix today!
