### ISSUE TITLE
how do i run on mac

### ISSUE THREAD

**Issue by kalaab69** [AquaPlaysYT/Fn_Bot_Commands#6]
is it possible to run the bot on osx?

**Comment by thebridgesofmadisoncounty** [comment]
I'm sure there's a node.js binary for MacOS/OSX, but if you can't get that working you can run it in the cloud using the billions of services out there (Heroku, UpTimeRobot, etc.)

**Comment by AquaPlaysYT** [comment]
Thank you ^ :)
